services:
  marlin-search-indexer:
    build: .
    container_name: marlin-search-indexer
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}
      - MEILISEARCH_URL=http://marlin-search-meilisearch:7700
      - SCRAPE_INTERVAL_MINUTES=${SCRAPE_INTERVAL_MINUTES}
      - EXPRESS_AUTH_TOKEN=${EXPRESS_AUTH_TOKEN}
      - BATCH_SIZE=${BATCH_SIZE}
    depends_on:
      - marlin-search-meilisearch
    networks:
      - marlin-network

  marlin-search-meilisearch:
    image: getmeili/meilisearch:latest
    container_name: marlin-search-meilisearch
    ports:
      - "7707:7700"
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY}
    volumes:
      - meili_data:/meili_data
    networks:
      - marlin-network

volumes:
  meili_data:
networks:
  marlin-network:
